import {InputToSqlMapping} from "./datatypes";

export const salesMappingDataMapping: InputToSqlMapping[] = [
  {
    xlsxAddress: 'A',
    dataType: 'string',
    sqlLabel: 'customer_ship_to',
    sqlType: 'varchar(15)',
  },
  {
    xlsxAddress: 'B',
    dataType: 'string',
    sqlLabel: 'postal',
    sqlType: 'varchar(12)',
  },
  {
    xlsxAddress: 'C',
    dataType: 'string',
    sqlLabel: 'zipcode',
    sqlType: 'varchar(8)',
  },
  {
    xlsxAddress: 'D',
    dataType: 'string',
    sqlLabel: 'primary_territory',
    sqlType: 'varchar(40)',
  },
  {
    xlsxAddress: 'E',
    dataType: 'string',
    sqlLabel: 'primary_name',
    sqlType: 'varchar(50)',
  },
  {
    xlsxAddress: 'F',
    dataType: 'string',
    sqlLabel: 'kae_territory',
    sqlType: 'varchar(40)',
  },
  {
    xlsxAddress: 'G',
    dataType: 'string',
    sqlLabel: 'kae_name',
    sqlType: 'varchar(50)',
  },
  {
    xlsxAddress: 'H',
    dataType: 'string',
    sqlLabel: 'secondary_territory',
    sqlType: 'varchar(40)',
  },
  {
    xlsxAddress: 'I',
    dataType: 'string',
    sqlLabel: 'secondary_name',
    sqlType: 'varchar(50)',
  },
  {
    xlsxAddress: 'J',
    dataType: 'string',
    sqlLabel: 'vrs_territory',
    sqlType: 'varchar(40)',
  },
  {
    xlsxAddress: 'K',
    dataType: 'string',
    sqlLabel: 'vrs_name',
    sqlType: 'varchar(50)',
  },
  {
    xlsxAddress: 'L',
    dataType: 'string',
    sqlLabel: 'rtm_territory',
    sqlType: 'varchar(40)',
  },
  {
    xlsxAddress: 'M',
    dataType: 'string',
    sqlLabel: 'rtm_name',
    sqlType: 'varchar(50)',
  },
  {
    xlsxAddress: 'N',
    dataType: 'string',
    sqlLabel: 'cos_territory',
    sqlType: 'varchar(40)',
  },
  {
    xlsxAddress: 'O',
    dataType: 'string',
    sqlLabel: 'cos_name',
    sqlType: 'varchar(50)',
  },
  {
    xlsxAddress: 'P',
    dataType: 'string',
    sqlLabel: 'atm_territory',
    sqlType: 'varchar(40)',
  },
  {
    xlsxAddress: 'Q',
    dataType: 'string',
    sqlLabel: 'atm_name',
    sqlType: 'varchar(50)',
  },
  {
    xlsxAddress: 'R',
    dataType: 'string',
    sqlLabel: 'ases_territory',
    sqlType: 'varchar(40)',
  },
  {
    xlsxAddress: 'S',
    dataType: 'string',
    sqlLabel: 'ases_name',
    sqlType: 'varchar(50)',
  },
  {
    xlsxAddress: 'T',
    dataType: 'string',
    sqlLabel: 'cust_adv_territory',
    sqlType: 'varchar(40)',
  },
  {
    xlsxAddress: 'U',
    dataType: 'string',
    sqlLabel: 'cust_adv_name',
    sqlType: 'varchar(50)',
  },
  {
    xlsxAddress: 'V',
    dataType: 'string',
    sqlLabel: 'eas_territory',
    sqlType: 'varchar(40)',
  },
  {
    xlsxAddress: 'W',
    dataType: 'string',
    sqlLabel: 'eas_name',
    sqlType: 'varchar(50)',
  },
  {
    xlsxAddress: 'X',
    dataType: 'string',
    sqlLabel: 'vs_territory',
    sqlType: 'varchar(40)',
  },
  {
    xlsxAddress: 'Y',
    dataType: 'string',
    sqlLabel: 'vs_name',
    sqlType: 'varchar(50)',
  },
  {
    xlsxAddress: 'Z',
    dataType: 'string',
    sqlLabel: 'pds_territory',
    sqlType: 'varchar(40)',
  },
  {
    xlsxAddress: 'AA',
    dataType: 'string',
    sqlLabel: 'pds_name',
    sqlType: 'varchar(50)',
  },
  {
    xlsxAddress: 'AB',
    dataType: 'string',
    sqlLabel: 'ent_territory',
    sqlType: 'varchar(40)',
  },
  {
    xlsxAddress: 'AC',
    dataType: 'string',
    sqlLabel: 'ent_name',
    sqlType: 'varchar(50)',
  },
  {
    xlsxAddress: 'AD',
    dataType: 'string',
    sqlLabel: 'iss_territory',
    sqlType: 'varchar(40)',
  },
  {
    xlsxAddress: 'AE',
    dataType: 'string',
    sqlLabel: 'iss_name',
    sqlType: 'varchar(50)',
  },
  {
    xlsxAddress: 'AF',
    dataType: 'string',
    sqlLabel: 'sir_territory',
    sqlType: 'varchar(40)',
  },
  {
    xlsxAddress: 'AG',
    dataType: 'string',
    sqlLabel: 'sir_name',
    sqlType: 'varchar(50)',
  },
  {
    xlsxAddress: 'AH',
    dataType: 'string',
    sqlLabel: 'clae_territory',
    sqlType: 'varchar(40)',
  },
  {
    xlsxAddress: 'AI',
    dataType: 'string',
    sqlLabel: 'clae_name',
    sqlType: 'varchar(50)',
  },
  {
    xlsxAddress: 'AJ',
    dataType: 'string',
    sqlLabel: 'other_territory',
    sqlType: 'varchar(40)',
  },
  {
    xlsxAddress: 'AK',
    dataType: 'string',
    sqlLabel: 'other_name',
    sqlType: 'varchar(50)',
  },
];
